// ============================================================
// products.js — All product data for BoringThings
// To add a new shoe: just add a new object to this array.
// The site will automatically display it everywhere.
// ============================================================

export const PRODUCTS = [

  // ── HOKA ──────────────────────────────────────────────────
  {
    id: 1,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Clifton 9',
    category: 'shoes',
    price: 135,
    origPrice: 165,
    emoji: '👟',
    rating: 4.8,
    reviews: 2341,
    tags: ['sale'],
    featured: true,
    trending: false,
    desc: 'The Clifton 9 delivers a supremely cushioned, lightweight ride. Redesigned midsole foam for enhanced cushioning and durability on every run.',
    colors: ['Black', 'White', 'Coral'],
    specs: { Weight: '8.9 oz', Drop: '5mm', Type: 'Road Running', Surface: 'Road' },
  },
  {
    id: 2,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Bondi 8',
    category: 'shoes',
    price: 165,
    origPrice: 200,
    emoji: '🏃',
    rating: 4.9,
    reviews: 3102,
    tags: ['sale'],
    featured: true,
    trending: true,
    desc: 'Maximum cushioning for maximum comfort. The Bondi 8 is the plushest road shoe yet with an extended heel design and meta-rocker geometry.',
    colors: ['Navy', 'White', 'Yellow'],
    specs: { Weight: '10.8 oz', Drop: '4mm', Type: 'Max Cushion', Surface: 'Road' },
  },
  {
    id: 3,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Mach 6',
    category: 'shoes',
    price: 145,
    origPrice: null,
    emoji: '⚡',
    rating: 4.7,
    reviews: 891,
    tags: ['hot'],
    featured: false,
    trending: true,
    desc: 'Engineered for speed. The Mach 6 features a full-length carbon-injected plate for an explosive push-off every stride.',
    colors: ['Lime', 'Black', 'Blue'],
    specs: { Weight: '7.8 oz', Drop: '5mm', Type: 'Speed', Surface: 'Road' },
  },
  {
    id: 4,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Speedgoat 5',
    category: 'shoes',
    price: 155,
    origPrice: null,
    emoji: '🏔️',
    rating: 4.8,
    reviews: 1423,
    tags: ['new'],
    featured: false,
    trending: true,
    desc: 'Built for the most technical trails. The Speedgoat 5 features Vibram Megagrip outsole and a wide toe box for confident footing.',
    colors: ['Teal', 'Orange', 'Black'],
    specs: { Weight: '9.4 oz', Drop: '4mm', Type: 'Trail', Surface: 'Trail' },
  },
  {
    id: 5,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Arahi 7',
    category: 'shoes',
    price: 140,
    origPrice: 160,
    emoji: '🔵',
    rating: 4.6,
    reviews: 987,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Stability without the bulk. The Arahi 7 uses an H-Frame design to guide your stride with a lightweight, cushioned feel.',
    colors: ['Blue', 'White', 'Grey'],
    specs: { Weight: '9.2 oz', Drop: '5mm', Type: 'Stability', Surface: 'Road' },
  },
  {
    id: 6,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Running Cap',
    category: 'hats',
    price: 38,
    origPrice: 45,
    emoji: '🧢',
    rating: 4.5,
    reviews: 412,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Lightweight, moisture-wicking running cap with reflective Hoka logo and ventilation panels for warm-weather runs.',
    colors: ['Black', 'White'],
    specs: { Material: 'Recycled Polyester', Brim: 'Short', Fit: 'Adjustable' },
  },
  {
    id: 7,
    brand: 'hoka',
    brandName: 'Hoka',
    name: 'Sport Duffel Bag',
    category: 'accessories',
    price: 65,
    origPrice: null,
    emoji: '🎒',
    rating: 4.6,
    reviews: 223,
    tags: [],
    featured: false,
    trending: false,
    desc: 'Versatile 22L sport bag with dedicated shoe compartment, laptop sleeve, and water-resistant exterior.',
    colors: ['Black', 'Navy'],
    specs: { Volume: '22L', Material: 'Ripstop Nylon', Pockets: '5' },
  },

  // ── NEW BALANCE ───────────────────────────────────────────
  {
    id: 8,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'Fresh Foam X 1080v13',
    category: 'shoes',
    price: 165,
    origPrice: null,
    emoji: '👟',
    rating: 4.9,
    reviews: 1872,
    tags: ['new'],
    featured: true,
    trending: true,
    desc: 'The 1080 is the most cushioned neutral trainer, designed for everyday long runs with the new Fresh Foam X midsole compound.',
    colors: ['Black', 'Grey', 'White'],
    specs: { Weight: '9.7 oz', Drop: '6mm', Type: 'Daily Trainer', Surface: 'Road' },
  },
  {
    id: 9,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: '990v6',
    category: 'shoes',
    price: 185,
    origPrice: 220,
    emoji: '🏅',
    rating: 4.8,
    reviews: 2203,
    tags: ['sale'],
    featured: true,
    trending: false,
    desc: 'Made in USA. A classic evolved. The 990v6 blends premium pigskin suede with breathable mesh for iconic style and all-day performance.',
    colors: ['Grey', 'Navy', 'Brown'],
    specs: { Weight: '11.2 oz', Drop: '12mm', Type: 'Lifestyle', Surface: 'All-Day' },
  },
  {
    id: 10,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'FuelCell SuperComp Elite v4',
    category: 'shoes',
    price: 250,
    origPrice: null,
    emoji: '🚀',
    rating: 4.7,
    reviews: 654,
    tags: ['hot'],
    featured: false,
    trending: true,
    desc: 'Carbon plate racing shoe with FuelCell foam for maximum energy return. Built for race day PBs.',
    colors: ['White', 'Gold'],
    specs: { Weight: '7.3 oz', Drop: '7mm', Type: 'Racing', Surface: 'Road' },
  },
  {
    id: 11,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'Fresh Foam 860v14',
    category: 'shoes',
    price: 140,
    origPrice: 155,
    emoji: '🟡',
    rating: 4.7,
    reviews: 1134,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Stability meets comfort. The 860v14 offers reliable medial post support wrapped in ultra-soft Fresh Foam X cushioning.',
    colors: ['Yellow', 'Black', 'White'],
    specs: { Weight: '10.1 oz', Drop: '10mm', Type: 'Stability', Surface: 'Road' },
  },
  {
    id: 12,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'Hierro v8 Trail',
    category: 'shoes',
    price: 135,
    origPrice: null,
    emoji: '🌲',
    rating: 4.6,
    reviews: 543,
    tags: ['new'],
    featured: false,
    trending: true,
    desc: 'Rugged trail runner with Vibram outsole and Fresh Foam midsole. Ready for whatever the mountain throws at you.',
    colors: ['Green', 'Black', 'Tan'],
    specs: { Weight: '10.5 oz', Drop: '8mm', Type: 'Trail', Surface: 'Trail/Offroad' },
  },
  {
    id: 13,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'NB Athletics Cap',
    category: 'hats',
    price: 32,
    origPrice: null,
    emoji: '🧢',
    rating: 4.4,
    reviews: 318,
    tags: [],
    featured: false,
    trending: false,
    desc: 'Classic 6-panel structured cap with embroidered NB logo. Timeless style for everyday wear.',
    colors: ['Grey', 'Black', 'Navy'],
    specs: { Material: 'Cotton Twill', Brim: 'Curved', Fit: 'Snapback' },
  },
  {
    id: 14,
    brand: 'newbalance',
    brandName: 'New Balance',
    name: 'Running Belt',
    category: 'accessories',
    price: 28,
    origPrice: 35,
    emoji: '🎽',
    rating: 4.3,
    reviews: 187,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Lightweight running belt with secure zip pockets for phone, keys and energy gels. Adjustable and bounce-free.',
    colors: ['Black'],
    specs: { Pockets: '3', Material: 'Nylon', Fit: 'Adjustable' },
  },

  // ── ASICS ─────────────────────────────────────────────────
  {
    id: 15,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Gel-Kayano 31',
    category: 'shoes',
    price: 160,
    origPrice: 190,
    emoji: '👟',
    rating: 4.8,
    reviews: 1654,
    tags: ['sale'],
    featured: true,
    trending: false,
    desc: 'Legendary stability with next-gen cushioning. The Kayano 31 features FF BLAST+ ECO midsole foam and PureGEL technology for overpronators.',
    colors: ['Black', 'Blue', 'Pink'],
    specs: { Weight: '9.5 oz', Drop: '10mm', Type: 'Stability', Surface: 'Road' },
  },
  {
    id: 16,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Gel-Nimbus 26',
    category: 'shoes',
    price: 165,
    origPrice: null,
    emoji: '🌟',
    rating: 4.9,
    reviews: 2876,
    tags: ['new'],
    featured: true,
    trending: true,
    desc: 'Our most plush neutral trainer. The Nimbus 26 delivers a cloud-like ride with PureGEL technology and FF BLAST PLUS ECO foam.',
    colors: ['White', 'Sage', 'Midnight'],
    specs: { Weight: '10.7 oz', Drop: '8mm', Type: 'Max Cushion', Surface: 'Road' },
  },
  {
    id: 17,
    brand: 'asics',
    brandName: 'Asics',
    name: 'MetaSpeed Sky+ Carbon',
    category: 'shoes',
    price: 250,
    origPrice: null,
    emoji: '💨',
    rating: 4.7,
    reviews: 443,
    tags: ['hot'],
    featured: false,
    trending: true,
    desc: 'Engineered for stride runners. Carbon plate racing shoe with GUIDESOLE technology for maximum forward propulsion on race day.',
    colors: ['White', 'Blue'],
    specs: { Weight: '7.9 oz', Drop: '5mm', Type: 'Racing', Surface: 'Road' },
  },
  {
    id: 18,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Gel-Cumulus 26',
    category: 'shoes',
    price: 130,
    origPrice: 145,
    emoji: '☁️',
    rating: 4.7,
    reviews: 1328,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Versatile daily trainer with PureGEL technology and FF BLAST foam for a smooth, adaptable ride on any road.',
    colors: ['Cement', 'Black', 'Lavender'],
    specs: { Weight: '9.2 oz', Drop: '10mm', Type: 'Neutral', Surface: 'Road' },
  },
  {
    id: 19,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Gel-Trabuco 12 Trail',
    category: 'shoes',
    price: 120,
    origPrice: null,
    emoji: '🏕️',
    rating: 4.5,
    reviews: 672,
    tags: [],
    featured: false,
    trending: false,
    desc: 'Rugged trail protection with ORTHOLITE sockliner and AHAR+ outsole rubber for durability on rocky terrain.',
    colors: ['Olive', 'Black', 'Orange'],
    specs: { Weight: '10.2 oz', Drop: '10mm', Type: 'Trail', Surface: 'Trail' },
  },
  {
    id: 20,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Performance Hat',
    category: 'hats',
    price: 36,
    origPrice: 42,
    emoji: '🧢',
    rating: 4.5,
    reviews: 289,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Technical running hat with reflective details, sweat-wicking headband, and mesh ventilation panels.',
    colors: ['Black', 'Blue'],
    specs: { Material: 'Polyester', Brim: 'Short', Fit: 'Adjustable' },
  },
  {
    id: 21,
    brand: 'asics',
    brandName: 'Asics',
    name: 'Training Gear Bag',
    category: 'accessories',
    price: 55,
    origPrice: null,
    emoji: '🎒',
    rating: 4.4,
    reviews: 156,
    tags: [],
    featured: false,
    trending: false,
    desc: '18L training bag with ventilated shoe pocket, water bottle holders, and padded shoulder straps.',
    colors: ['Black', 'Navy'],
    specs: { Volume: '18L', Material: 'Polyester', Pockets: '4' },
  },

  // ── ON CLOUD ──────────────────────────────────────────────
  {
    id: 22,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Cloudmonster 2',
    category: 'shoes',
    price: 170,
    origPrice: null,
    emoji: '👟',
    rating: 4.8,
    reviews: 1103,
    tags: ['new'],
    featured: true,
    trending: true,
    desc: 'Bigger clouds, bigger feel. The Cloudmonster 2 features extra-large CloudTec pods for a cushioned, springy ride that never quits.',
    colors: ['Black', 'Orange', 'White'],
    specs: { Weight: '9.2 oz', Drop: '6mm', Type: 'Cushioned', Surface: 'Road' },
  },
  {
    id: 23,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Cloudflow 4',
    category: 'shoes',
    price: 140,
    origPrice: 160,
    emoji: '☁️',
    rating: 4.7,
    reviews: 987,
    tags: ['sale'],
    featured: false,
    trending: true,
    desc: 'Designed for tempo runs. The Cloudflow 4 delivers speed with its lightweight Helion superfoam and responsive CloudTec outsole.',
    colors: ['Glacier', 'Navy', 'Berry'],
    specs: { Weight: '8.3 oz', Drop: '6mm', Type: 'Speed', Surface: 'Road' },
  },
  {
    id: 24,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Cloud 5',
    category: 'shoes',
    price: 130,
    origPrice: null,
    emoji: '🌤️',
    rating: 4.6,
    reviews: 2543,
    tags: ['hot'],
    featured: true,
    trending: false,
    desc: 'The everyday sneaker. Iconic CloudTec sole for soft landings and explosive takeoffs. Versatile from street to trail.',
    colors: ['White', 'Black', 'Cream'],
    specs: { Weight: '8.8 oz', Drop: '6mm', Type: 'Everyday', Surface: 'Road/Street' },
  },
  {
    id: 25,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Cloudultra 2 Trail',
    category: 'shoes',
    price: 180,
    origPrice: null,
    emoji: '⛰️',
    rating: 4.7,
    reviews: 567,
    tags: ['new'],
    featured: false,
    trending: false,
    desc: 'Ultra-distance trail shoe with multi-directional CloudTec for grip and cushioning across any terrain.',
    colors: ['Midnight', 'Hay', 'Black'],
    specs: { Weight: '10.1 oz', Drop: '6mm', Type: 'Trail Ultra', Surface: 'Trail' },
  },
  {
    id: 26,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Cloudswift 3',
    category: 'shoes',
    price: 150,
    origPrice: 165,
    emoji: '🌀',
    rating: 4.6,
    reviews: 812,
    tags: ['sale'],
    featured: false,
    trending: true,
    desc: 'City runner meets all-day sneaker. The Cloudswift 3 wraps your foot in Zero-Gravity foam for effortless transitions.',
    colors: ['Rose', 'Black', 'Sand'],
    specs: { Weight: '8.5 oz', Drop: '7mm', Type: 'Urban', Surface: 'Road/Street' },
  },
  {
    id: 27,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Lightweight Cap',
    category: 'hats',
    price: 45,
    origPrice: null,
    emoji: '🧢',
    rating: 4.6,
    reviews: 342,
    tags: [],
    featured: false,
    trending: false,
    desc: 'Ultra-lightweight 5-panel cap with On Cloud logo. Packable design for travel, moisture-wicking sweatband.',
    colors: ['White', 'Black'],
    specs: { Material: 'Recycled Nylon', Brim: 'Curved', Fit: 'Adjustable' },
  },
  {
    id: 28,
    brand: 'oncloud',
    brandName: 'On Cloud',
    name: 'Running Vest',
    category: 'accessories',
    price: 80,
    origPrice: 95,
    emoji: '🎽',
    rating: 4.7,
    reviews: 267,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Lightweight running vest with 1.5L hydration pack and multiple pockets for fueling on long runs.',
    colors: ['Black', 'Blue'],
    specs: { Volume: '1.5L', Material: 'Stretch Woven', Pockets: '6' },
  },

  // ── BROOKS ────────────────────────────────────────────────
  {
    id: 29,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Ghost 16',
    category: 'shoes',
    price: 140,
    origPrice: null,
    emoji: '👟',
    rating: 4.8,
    reviews: 4231,
    tags: ['new'],
    featured: true,
    trending: true,
    desc: "The world's best-selling running shoe returns. The Ghost 16 offers soft, smooth cushioning for easy everyday runs, whatever your pace.",
    colors: ['Black', 'Grey', 'Purple'],
    specs: { Weight: '9.6 oz', Drop: '12mm', Type: 'Neutral', Surface: 'Road' },
  },
  {
    id: 30,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Glycerin 21',
    category: 'shoes',
    price: 160,
    origPrice: 185,
    emoji: '💜',
    rating: 4.9,
    reviews: 1987,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: "Brooks most luxurious running shoe. Nitrogen-infused DNA LOFT v3 cushioning for an ultra-plush, pressure-free ride.",
    colors: ['White', 'Blue', 'Navy'],
    specs: { Weight: '10.1 oz', Drop: '10mm', Type: 'Max Cushion', Surface: 'Road' },
  },
  {
    id: 31,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Hyperion Max 2',
    category: 'shoes',
    price: 200,
    origPrice: null,
    emoji: '⚡',
    rating: 4.7,
    reviews: 623,
    tags: ['hot'],
    featured: false,
    trending: true,
    desc: 'Maximum velocity. The Hyperion Max 2 features a carbon fiber plate and super-critical DNA FLASH midsole for race-day speed.',
    colors: ['Coral', 'Black', 'Lime'],
    specs: { Weight: '7.8 oz', Drop: '8mm', Type: 'Racing', Surface: 'Road' },
  },
  {
    id: 32,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Adrenaline GTS 24',
    category: 'shoes',
    price: 130,
    origPrice: 150,
    emoji: '🔷',
    rating: 4.8,
    reviews: 3109,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: "America's #1 stability shoe. The Adrenaline GTS 24 uses GuideRails to keep excess movement in check for a smooth, supported ride.",
    colors: ['Blue', 'White', 'Black'],
    specs: { Weight: '9.9 oz', Drop: '12mm', Type: 'Stability', Surface: 'Road' },
  },
  {
    id: 33,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Cascadia 17 Trail',
    category: 'shoes',
    price: 130,
    origPrice: null,
    emoji: '🌿',
    rating: 4.7,
    reviews: 1087,
    tags: ['new'],
    featured: false,
    trending: true,
    desc: 'Built for the long haul on technical trails. The Cascadia 17 features rock plate protection and BioMoGo DNA midsole cushioning.',
    colors: ['Forest', 'Black', 'Orange'],
    specs: { Weight: '10.7 oz', Drop: '8mm', Type: 'Trail', Surface: 'Trail' },
  },
  {
    id: 34,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Podium Hat',
    category: 'hats',
    price: 30,
    origPrice: 36,
    emoji: '🧢',
    rating: 4.4,
    reviews: 198,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Classic Brooks Podium hat with moisture management sweatband and rear adjustable strap for a perfect fit.',
    colors: ['Black', 'White', 'Grey'],
    specs: { Material: 'Polyester', Brim: 'Curved', Fit: 'Adjustable' },
  },
  {
    id: 35,
    brand: 'brooks',
    brandName: 'Brooks',
    name: 'Run Happy Socks (3-pack)',
    category: 'accessories',
    price: 22,
    origPrice: 28,
    emoji: '🧦',
    rating: 4.6,
    reviews: 891,
    tags: ['sale'],
    featured: false,
    trending: false,
    desc: 'Run Happy Socks engineered with strategic cushioning, mesh ventilation zones, and seamless toe construction.',
    colors: ['Multi'],
    specs: { Material: 'Nylon/Polyester', Height: 'Ankle', Pack: '3 pairs' },
  },
]

// ── Derived helpers (used in App.jsx) ──────────────────────

/** All unique brand keys */
export const BRANDS = [
  { key: 'all',        label: 'Show All'    },
  { key: 'hoka',       label: 'Hoka'        },
  { key: 'newbalance', label: 'New Balance' },
  { key: 'asics',      label: 'Asics'       },
  { key: 'oncloud',    label: 'On Cloud'    },
  { key: 'brooks',     label: 'Brooks'      },
]

/** Filter products by brand key */
export function getByBrand(brand) {
  return brand === 'all' ? PRODUCTS : PRODUCTS.filter(p => p.brand === brand)
}

/** Get featured products */
export function getFeatured(limit = 4) {
  return PRODUCTS.filter(p => p.featured).slice(0, limit)
}

/** Get trending products */
export function getTrending(limit = 4) {
  return PRODUCTS.filter(p => p.trending).slice(0, limit)
}

/** Get recommendations: same brand or category, excluding current */
export function getRecs(productId, limit = 4) {
  const current = PRODUCTS.find(p => p.id === productId)
  if (!current) return []
  return PRODUCTS
    .filter(p => p.id !== productId && (p.brand === current.brand || p.category === current.category))
    .slice(0, limit)
}

/** Fuzzy search across name, brand, category, description */
export function searchProducts(query, limit = 6) {
  const q = query.toLowerCase().trim()
  if (q.length < 2) return []
  return PRODUCTS.filter(p => {
    const str = `${p.name} ${p.brandName} ${p.category} ${p.desc}`.toLowerCase()
    if (str.includes(q)) return true
    for (let i = 0; i <= q.length - 3; i++) {
      if (str.includes(q.slice(i, i + 3))) return true
    }
    return false
  }).slice(0, limit)
}

/** Get sizes for a product category */
export function getSizes(category) {
  if (category === 'shoes') return ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12']
  if (category === 'hats')  return ['S/M', 'L/XL']
  return ['One Size']
}
